services:
  postgres_dev:
    container_name: 'postgres-studyconnect-dev'
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:5432'

  adminer:
    image: adminer
    container_name: 'adminer-studyconnect'
    restart: always
    ports:
      - "7777:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres_dev
    depends_on:
      - postgres_dev
